palette = "coolor"

format = """
$username\
[ @ ](fg:9)\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
[î‚°](fg:darkslate bg:#)\
\n$character"""

right_format = """
$python\
$nodejs\
$rust\
$haskell\
$lua\
$c\

$golang\
$php\

[î‚¾](fg:5)\
[î‚¸](fg:5)\
$time\
[î‚¾](fg:5)\
[î‚¸](fg:5)\
$battery\
[î‚¾](fg:5)\
[î‚¸](fg:5)\
$cmd_duration\

"""

[palettes.coolor]
night = '#00120b'
darkslate = '#35605a'
mydark = '#212736'
ddslate = '#2b4f4a'
slate = '#6b818c'
lavender = '#d8e4ff'
sgreen = '#31e981'
mint = '#85e7c0'
pblue = '#a2b3c6'
mgreen = '#507173'
jade = '#33a56e'
pink = '#ff70fd'

[palettes.gren]
darkgreen = '#166446'
lightgreen = '#1d865e'
lightgray = '#e3e5e5'
darkgray = '#394260'

[username]
show_always = true
style_user = "fg:6"
style_root = "fg:1"
format = '[î°• $user]($style)'
disabled = false

[directory]
style = "fg:249"
format = "[$path ]($style)"
truncation_length = 2
truncation_symbol = "îªƒ/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

# GIT STUFF

[git_branch]
symbol = "ï˜"
style = ""
format = '[[[on](fg:6) $symbol $branch ](fg:3)]($style)'

[git_status]
style = "bold green"
up_to_date = "âœ“"
staged = " +$count"
modified = " !$count"
untracked = " ?$count"
stashed = " â‰¡$count"
renamed = " Â»$count"
deleted = " âœ˜$count"
conflicted = " =$count"
ahead = " â‡¡$count"
behind = " â‡£$count"
diverged = " â‡•$ahead_count/$behind_count"
ignore_submodules = true
format = '([$up_to_date$staged$modified$untracked$stashed$renamed$deleted$conflicted$ahead_behind]($style) )'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

# LANGUAGES

[nodejs]
symbol = "îœ˜"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:6)]($style)'

[rust]
symbol = "î¨"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:1)]($style)'

[golang]
symbol = "î˜§"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:38)]($style)'

[python]
symbol = "î´›"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:28)]($style)'

[c]
symbol = "c"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:20)]($style)'

[haskell]
symbol = "î·"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:96)]($style)'

[lua]
symbol = "î˜ "
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:27)]($style)'

[bun]
symbol = "î¾‚"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:3)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:mydark"
format = '[[ $symbol ($version) ](fg:19)]($style)'

[cpp]
disabled = false
symbol = "î™†"
format = 'via [$symbol ($version)](fg:20)'

[zig]
symbol = "ó±‹"
format = '[[ $symbol ($version) ](fg:80)]'

# UTILITIES

[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = ""
format = '[[ ïº $time ](fg:15)]($style)'


[battery]
full_symbol = 'îŒ• '
charging_symbol = 'ó±‹ '
symbol = 'ó±‹ '
discharging_symbol = 'ó±Œ '
format = '[ $symbol$percentage ]($style)'
style = "fg:3"

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 50
style = 'bold yellow'

[[battery.display]]
threshold = 99
style = 'bold green'

[cmd_duration]
min_time = 1
format = 'took [$duration](bold yellow)'

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
